### ISSUE TITLE
handle expired token

### ISSUE THREAD

**Issue by altesockensuppe** [adfinis/timedctl#31]
if timedctl is used in swaybar for example, the timedctl process hangs every morning because the token has expired. The process must be killed manually so that timedctl can be executed again.
```
$ timedctl ac show
Traceback (most recent call last):
  File "/usr/bin/timedctl", line 5, in <module>
    from timedctl.timedctl import timedctl
  File "/usr/lib/python3.11/site-packages/timedctl/timedctl.py", line 171, in <module>
    timed = client_setup()
            ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/timedctl/timedctl.py", line 70, in client_setup
    token = oidc_client.authorize()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libtimed/oidc.py", line 127, in authorize
    if self.start_browser_flow():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libtimed/oidc.py", line 61, in start_browser_flow
    server = http.server.HTTPServer(("localhost", 5000), OIDCHTTPRequestHandler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```
```
$ ps aux | grep timed
matthia+  122222  0.0  0.0   7524  3328 tty2     S    00:13   0:00 sh -c timedctl activity show | cut -d: -f2-
matthia+  122223  0.0  0.1 308532 67364 tty2     SLl  00:13   0:00 /usr/bin/python /usr/bin/timedctl activity show


$ sudo strace -p 122222
[sudo] password for matthiash: 
strace: Process 122222 attached
wait4(-1, 
```

**Comment by gianklug** [comment]
I'll add a `--no-renew-token` option that'll just exit with an error messages to be used in such cases.

**Comment by gianklug** [comment]
Fixed in latest release!
