### ISSUE TITLE
Bug in Version 5.3.0

### ISSUE THREAD

**Issue by eyenx** [adfinis/timedctl#43]
When using Version 5.3.0 of the timedctl I get a traceback error when using `activity show`

```
Traceback (most recent call last):
  File "/usr/bin/timedctl", line 8, in <module>
    sys.exit(timedctl())
             ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/timedctl/timedctl.py", line 625, in show_activity
    f"Current activity: {format_activity(activity)}{comment} (Since "
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/timedctl/timedctl.py", line 168, in format_activity
    task_obj = activity_obj["relationships"]["task"]
```

**Comment by gianklug** [comment]
Fixed in v5.3.1, sorry

Thinking about implementing a `timedctl-nightly` branch and pushing releases after testing only...
